export const apiGetListUser = "api/user/getListUser"
export const apiGetDetailUser = "api/user/getDetailUser"
export const apiAddUser = "api/user/addUser"
export const apiUpdateUser = "api/user/updateUser"
export const apiDeleteUser = "api/user/deleteUser"
export const apiChangeStatus = "api/user/changeStatus"
export const apiResetPassword = "api/user/resetPassword"
export const apiExportExcel = "api/user/exportExcel"
